import Device from './Device';
import BleManager from 'react-native-ble-manager';
import {bleManagerEmitter} from './bleScanner';
import {StateInfo} from './types';

const WLED_BLE_MAIN_SERVICE_ID = 'BEE30000-A2EB-4F7A-889B-13192C8C1819';
const WLED_BLE_MAIN_BLE_ON_ID = 'BEE30001-A2EB-4F7A-889B-13192C8C1819';

const WLED_BLE_DATA_SERVICE_ID = 'BEE30100-A2EB-4F7A-889B-13192C8C1819';
const WLED_BLE_STATE_INFO_DATA_ID = 'BEE30101-A2EB-4F7A-889B-13192C8C1819';
const WLED_BLE_STATE_INFO_CONTROL_ID = 'BEE30102-A2EB-4F7A-889B-13192C8C1819';
const WLED_BLE_STATE_INFO_NOTIFY_ID = 'BEE30103-A2EB-4F7A-889B-13192C8C1819';

const CHUNK_LENGTH = 512;

interface Reqeust {
  messageBuffer: string;
  resolve: (value: string | PromiseLike<string>) => void;
  reject: (reason?: any) => void;
}

export class BleDevice extends Device {
  id: string = '';
  outstandingRequestMap: Record<string, Reqeust> = {};
  connected: boolean = false;
  si?: StateInfo = undefined;
  notifyBuffer = '';

  constructor(peripheral: any) {
    console.log('found ' + JSON.stringify(peripheral));
    super(peripheral.advertising.localName);
    this.id = peripheral.id;
  }

  convertString(value: string): Array<number> {
    const charCodeArr = [];

    for (let i = 0; i < value.length; i++) {
      let code = value.charCodeAt(i);
      charCodeArr.push(code);
    }

    return charCodeArr;
  }

  async connect(): Promise<void> {
    console.log('connecting');
    await BleManager.connect(this.id);
    bleManagerEmitter.addListener(
      'BleManagerDidUpdateValueForCharacteristic',
      (data: any) => {
        if (data.peripheral === this.id) {
          if (data.characteristic === WLED_BLE_STATE_INFO_NOTIFY_ID) {
            this.notifyBuffer += String.fromCharCode.apply(null, data.value);

            if (data.value.length !== CHUNK_LENGTH) {
              console.log(this.notifyBuffer);
              if (this.si) this.si.state = JSON.parse(this.notifyBuffer);
              this.notify(this.notifyBuffer);
              this.notifyBuffer = '';
            }
            return;
          }

          const request = this.outstandingRequestMap[data.characteristic];

          if (request) {
            request.messageBuffer += String.fromCharCode.apply(
              null,
              data.value,
            );
            if (data.value.length !== CHUNK_LENGTH) {
              request.resolve(request.messageBuffer);
              request.messageBuffer = '';
            }
          }
        }
      },
    );
    console.log('here1');
    await BleManager.retrieveServices(this.id);
    console.log('here2');
    await BleManager.startNotification(
      this.id,
      WLED_BLE_DATA_SERVICE_ID,
      WLED_BLE_STATE_INFO_DATA_ID,
    );
    console.log('here3');
    await BleManager.startNotification(
      this.id,
      WLED_BLE_DATA_SERVICE_ID,
      WLED_BLE_STATE_INFO_NOTIFY_ID,
    );
    console.log('here4');

    this.si = JSON.parse(await this.get('http://localhost/json/si'));
    this.connected = true;
    this.notify('{}');
  }

  read(
    path: string,
    resolve: (value: string | PromiseLike<string>) => void,
    reject: (reason?: any) => void,
  ) {
    switch (path) {
      case 'json/si':
        BleManager.write(
          this.id,
          WLED_BLE_DATA_SERVICE_ID,
          WLED_BLE_STATE_INFO_CONTROL_ID,
          this.convertString('r'),
        );
        this.outstandingRequestMap[WLED_BLE_STATE_INFO_DATA_ID] = {
          messageBuffer: '',
          resolve,
          reject,
        };
        break;
      default:
        resolve(JSON.stringify({}));
    }
  }

  async get(command: string): Promise<string> {
    const path = command.split('/').slice(3).join('/');

    console.log('reading ' + path);

    switch (path) {
      case 'json/palettes':
        return JSON.stringify([
          'Default',
          '* Random Cycle',
          '* Color 1',
          '* Colors 1&2',
          '* Color Gradient',
          '* Colors Only',
          'Party',
          'Cloud',
          'Lava',
          'Ocean',
          'Forest',
          'Rainbow',
          'Rainbow Bands',
          'Sunset',
          'Rivendell',
          'Breeze',
          'Red & Blue',
          'Yellowout',
          'Analogous',
          'Splash',
          'Pastel',
          'Sunset 2',
          'Beach',
          'Vintage',
          'Departure',
          'Landscape',
          'Beech',
          'Sherbet',
          'Hult',
          'Hult 64',
          'Drywet',
          'Jul',
          'Grintage',
          'Rewhi',
          'Tertiary',
          'Fire',
          'Icefire',
          'Cyane',
          'Light Pink',
          'Autumn',
          'Magenta',
          'Magred',
          'Yelmag',
          'Yelblu',
          'Orange & Teal',
          'Tiamat',
          'April Night',
          'Orangery',
          'C9',
          'Sakura',
          'Aurora',
          'Atlantica',
          'C9 2',
          'C9 New',
          'Temperature',
          'Aurora 2',
          'Retro Clown',
          'Candy',
          'Toxy Reaf',
          'Fairy Reaf',
          'Semi Blue',
          'Pink Candy',
          'Red Reaf',
          'Aqua Flash',
          'Yelblu Hot',
          'Lite Light',
          'Red Flash',
          'Blink Red',
          'Red Shift',
          'Red Tide',
          'Candy2',
        ]);
      case 'json/fxdata':
        return JSON.stringify([
          '',
          '!,Duty cycle;!,!;!',
          '!;!,!;!',
          '!,!;!,!;!',
          '!;;!',
          '!,Fade time;;!',
          '!,!;!,!;!',
          '!,!;;!',
          '!,Saturation;;!',
          '!,Size;;!',
          '!,# of dots;!,!,!;!',
          '!,# of dots;!,!,!;!',
          '!;!,!;!',
          '!,Gap size;!,!;!',
          '!,Gap size;,!;!',
          '!,Wave width;!,!;!',
          '!,Width;!,!;!',
          '!,!;!,!;!;;m12=0',
          'Repeat speed,Dissolve speed;!,!;!',
          'Repeat speed,Dissolve speed;,!;!',
          '!;!,!;!;;m12=0',
          '!,!;Bg,Fx;!;;m12=0',
          '!,!;Bg,Fx;!;;m12=0',
          '!;!,!;!',
          '!;,!;!',
          '!,!;!,!;!',
          'Frequency,Blink duration;!,!;!',
          '!,Width;!,!;!;;m12=1',
          '!,Width;!,!,!;!',
          '!,Width;!,,!;!',
          '!,Width;!,!;!',
          '!;Bg,Fx;!',
          '!;!,!;!',
          '!,Size;Bg;!',
          '!,Saturation;1,2,3;!',
          '!,US style;,!;!',
          '!;;!',
          '!,Width;!,!;!',
          '!,!;1,2,3;!;;sx=24,pal=50',
          '!,Zone size;;!',
          '!,Fade rate;!,!;!;;m12=0',
          '!,Fade rate;!,!;!',
          ',Frequency;!,!;!;12;ix=192,pal=11',
          '!,Spawning rate;!,!;!;12;ix=128,pal=0',
          '!,Width;!,!;!;;sx=0,ix=0,pal=11,m12=1',
          '!,!;!;!',
          '!,Spread;!,!;!;;ix=16',
          '!,Fade;!,!;!;;ix=16',
          '',
          '!,# of flashers;!,!;!',
          '!,Dot size;1,2,Bg;!',
          '!,!;!,!;!;;m12=0',
          '!,Wave width;L,!,R;!',
          '',
          '!,Size;1,2,3;!',
          '!;1,2,3;!',
          '!;1,2,3;!',
          '!,!;!,!;!',
          '!,!;!,!;!',
          '',
          '!,Fade rate;!,!,!;!;;m12=0',
          '!;;',
          '',
          '!;;',
          '!,Trail;;!;;sx=16,ix=240',
          'Cycle speed;;!',
          'Cooling,Spark rate;;!;1;sx=120,ix=64,m12=1',
          '!,Hue;!;!',
          '!;!;!;;sx=64',
          '!;!;!',
          '!;!;!',
          '!;!;!',
          '!;!;!',
          '!;!;!',
          'Fade speed,Spawn speed;;!;;m12=0',
          '!;Fx;!',
          '!,Trail length;!;!',
          '!,Trail length;!;!',
          '!,Smoothness;;!',
          '!,Wave #;,!;!',
          '!,Twinkle rate;;!',
          '!,Twinkle rate;;!',
          'Duration,Eye fade time;!,!;!;12',
          'Fg size,Bg size;Fg,!;!;;pal=0',
          ',Size;1,2,3;;;pal=0',
          ',Width;!,!;!',
          'Spread,Width;!,!;!',
          '!,!;;!;;m12=0',
          '!,!;!,!;!;1;sx=96,ix=224,pal=0',
          'Chance,Fragments;,!;!;;pal=11,m12=0',
          'Gravity,Firing side;!,!;!;12;pal=11,ix=128',
          'Gravity,# of balls;!,!,!;!;1;m12=1',
          '!,Trail;!,!,!;!',
          '!,Trail;!,!,!;!',
          '!,Trail;,,!;!',
          '!,!;!,!,!;!;;m12=1',
          'Gravity,# of drips;!,!;!;;m12=1',
          'Phase,!;!;!',
          ',% of fill,,,,One color;!,!;!',
          '!,Wave #;;!',
          '!,!;!,!;!;;m12=1',
          '!,Angle;;!;;pal=51',
          '!,!;!,!;!;;sx=96,ix=224,pal=0',
          ',!;!;;;m12=0',
          'Time [min],Width;;!;;sx=60',
          '!,!;!,!;!',
          '!,Intensity;!,!;!;;m12=0',
          '!,Scale;;!',
          '',
          '!,!;!,!;!',
          '!,Zones;;!;;m12=1',
          '!,Gap size;!,!;!',
          '!,# of shadows;!;!',
          '!,!;;!',
          '',
          'Shift speed,Blend speed;;!',
          '!,!;;',
          '!,!;;!',
          '!,Blur;;!;2',
          '!,Blur;;;2',
          'Fade rate,Blur;;!;2',
          '!,# blobs,Blur;!;!;2;c1=8',
          '!,Y Offset,Trail,Font size;!,!;!;2;ix=128,c1=0,rev=0,mi=0,rY=0,mY=0',
          'Fade,Blur;;;2',
          '',
          '',
          '',
          '',
          'Fade rate,# of pixels;!,!;!;1v;m12=0,si=0',
          '!,Sensitivity;!,!;!;1v;ix=64,m12=2,si=0',
          '!,# of balls;!,!;!;1v;m12=0,si=0',
          '!,Brightness;!,!;!;1v;ix=64,m12=2,si=1',
          'Rate of fall,Sensitivity;!,!;!;1v;ix=128,m12=2,si=0',
          'Phase,# of pixels;!,!;!;1v;sx=128,ix=128,m12=0,si=0',
          'Fade rate,Puddle size;!,!;!;1v;m12=0,si=0',
          'Fade rate,Max. length;!,!;!;1v;ix=128,m12=1,si=0',
          'Fade rate,Width;!,!;!;1v;ix=128,m12=2,si=0',
          'Time delay,Sound effect,Low bin,High bin,Pre-amp;;;1f;m12=2,si=0',
          'Time delay,Sound effect,Low bin,High bin,Sensivity;;;1f;m12=3,si=0',
          'Fade speed,Ripple decay,# of bands,,,Color bars;!,,Peaks;!;2f;c1=255,c2=64,pal=11,si=0',
          '!,Adjust color,Select bin,Volume (min);!,!;!;1f;c2=0,m12=2,si=0',
          'Fade rate,Starting color and # of pixels;;;1f;m12=0,si=0',
          '',
          '!,!;;;1v;m12=2,si=0',
          'Fade rate,Puddle size,Select bin,Volume (min);!,!;!;1v;c2=0,m12=0,si=0',
          'Speed of perlin movement,Fade rate;!,!;!;1f;m12=0,si=0',
          '!,Scale;;!;2',
          '!,# of pixels,Fade rate;!,!;!',
          'Fade rate,Max # of ripples,Select bin,Volume (min);!,!;!;1v;c2=0,m12=0,si=0',
          'X scale,Y scale;;!;2',
          ',,,,Blur;;!;2',
          '',
          'Scroll speed,Blur;;!;2',
          '!,Spawning rate,Trail,,,Custom color;Spawn,Trail;;2',
          '!;;!;2',
          'Fade rate,Starting color;!,!;!;1f;m12=0,si=0',
          'Rate of fall,Sensitivity;!,!;!;1v;ix=128,m12=2,si=0',
          'Rate of fall,Sensitivity;!,!;!;1v;ix=128,m12=3,si=0',
          'Rate of fall,Sensivity;!,!;!;1f;ix=128,m12=0,si=0',
          'Speed;;;1f;m12=2,si=0',
          'Scroll speed,,# of bands;;;2f;si=0',
          '',
          '!,Blur;;!;2',
          'Fade rate,Blur;!,Color mix;!;1f;m12=0,si=0',
          'Rotation speed,Blur amount;;!;2',
          'Amplification,Sensitivity;;!;2v;ix=64,si=0',
          'Variance,Brightness;;;2',
          'Speed,# of lines;;!;2',
          ',Max iterations per pixel,X center,Y center,Area size;!;!;2;ix=24,c1=128,c2=128,c3=16',
          '',
          '',
          '',
          '!;!,!;!;2',
          'X scale,Y scale;;!;2',
          '!,Scale;;;2',
          '!,Sensitivity,Blur;,Bg Swirl;!;2v;ix=64,si=0',
          'X frequency,Fade rate;!;!;2',
          'X frequency,Y frequency,Blur;;!;2',
          'Speed,,Fade,Blur;;!;2',
          'Hue speed,Effect speed;;',
          'X scale,Y scale,,,Speed;!;!;2',
          '!,Dot distance,Fade rate,Blur;;!;2',
          'Scroll speed,Y frequency;;!;2',
          'Fade rate,Outer Y freq.,Outer X freq.,Inner X freq.,Inner Y freq.;;;2',
          '!,Brightness variation,Starting color,Range of colors,Color variation;!;!',
          ';!,!;!;1f;m12=1,si=0',
          'Color speed,Dance;Head palette,Arms & Legs,Eyes & Mouth;Face palette;2f;si=0',
        ]);
      case 'json/effects':
        return JSON.stringify([
          'Solid',
          'Blink',
          'Breathe',
          'Wipe',
          'Wipe Random',
          'Random Colors',
          'Sweep',
          'Dynamic',
          'Colorloop',
          'Rainbow',
          'Scan',
          'Scan Dual',
          'Fade',
          'Theater',
          'Theater Rainbow',
          'Running',
          'Saw',
          'Twinkle',
          'Dissolve',
          'Dissolve Rnd',
          'Sparkle',
          'Sparkle Dark',
          'Sparkle+',
          'Strobe',
          'Strobe Rainbow',
          'Strobe Mega',
          'Blink Rainbow',
          'Android',
          'Chase',
          'Chase Random',
          'Chase Rainbow',
          'Chase Flash',
          'Chase Flash Rnd',
          'Rainbow Runner',
          'Colorful',
          'Traffic Light',
          'Sweep Random',
          'Chase 2',
          'Aurora',
          'Stream',
          'Scanner',
          'Lighthouse',
          'Fireworks',
          'Rain',
          'Tetrix',
          'Fire Flicker',
          'Gradient',
          'Loading',
          'RSVD',
          'Fairy',
          'Two Dots',
          'Fairytwinkle',
          'Running Dual',
          'RSVD',
          'Chase 3',
          'Tri Wipe',
          'Tri Fade',
          'Lightning',
          'ICU',
          'Multi Comet',
          'Scanner Dual',
          'Stream 2',
          'Oscillate',
          'Pride 2015',
          'Juggle',
          'Palette',
          'Fire 2012',
          'Colorwaves',
          'Bpm',
          'Fill Noise',
          'Noise 1',
          'Noise 2',
          'Noise 3',
          'Noise 4',
          'Colortwinkles',
          'Lake',
          'Meteor',
          'Meteor Smooth',
          'Railway',
          'Ripple',
          'Twinklefox',
          'Twinklecat',
          'Halloween Eyes',
          'Solid Pattern',
          'Solid Pattern Tri',
          'Spots',
          'Spots Fade',
          'Glitter',
          'Candle',
          'Fireworks Starburst',
          'Fireworks 1D',
          'Bouncing Balls',
          'Sinelon',
          'Sinelon Dual',
          'Sinelon Rainbow',
          'Popcorn',
          'Drip',
          'Plasma',
          'Percent',
          'Ripple Rainbow',
          'Heartbeat',
          'Pacifica',
          'Candle Multi',
          'Solid Glitter',
          'Sunrise',
          'Phased',
          'Twinkleup',
          'Noise Pal',
          'Sine',
          'Phased Noise',
          'Flow',
          'Chunchun',
          'Dancing Shadows',
          'Washing Machine',
          'RSVD',
          'Blends',
          'TV Simulator',
          'Dynamic Smooth',
          'Spaceships',
          'Crazy Bees',
          'Ghost Rider',
          'Blobs',
          'Scrolling Text',
          'Drift Rose',
          'RSVD',
          'RSVD',
          'RSVD',
          'RSVD',
          'Pixels',
          'Pixelwave',
          'Juggles',
          'Matripix',
          'Gravimeter',
          'Plasmoid',
          'Puddles',
          'Midnoise',
          'Noisemeter',
          'Freqwave',
          'Freqmatrix',
          'GEQ',
          'Waterfall',
          'Freqpixels',
          'RSVD',
          'Noisefire',
          'Puddlepeak',
          'Noisemove',
          'Noise2D',
          'Perlin Move',
          'Ripple Peak',
          'Firenoise',
          'Squared Swirl',
          'RSVD',
          'DNA',
          'Matrix',
          'Metaballs',
          'Freqmap',
          'Gravcenter',
          'Gravcentric',
          'Gravfreq',
          'DJ Light',
          'Funky Plank',
          'RSVD',
          'Pulser',
          'Blurz',
          'Drift',
          'Waverly',
          'Sun Radiation',
          'Colored Bursts',
          'Julia',
          'RSVD',
          'RSVD',
          'RSVD',
          'Game Of Life',
          'Tartan',
          'Polar Lights',
          'Swirl',
          'Lissajous',
          'Frizzles',
          'Plasma Ball',
          'Flow Stripe',
          'Hiphotic',
          'Sindots',
          'DNA Spiral',
          'Black Hole',
          'Wavesins',
          'Rocktaves',
          'Akemi',
        ]);
      case 'presets.json':
        return JSON.stringify({
          '0': {},
          '1': {
            on: true,
            bri: 128,
            transition: 7,
            mainseg: 0,
            seg: [
              {
                id: 0,
                start: 0,
                stop: 300,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [27, 32, 182],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 2,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
            ],
            n: 'test',
          },
          '2': {
            on: true,
            bri: 128,
            transition: 7,
            mainseg: 0,
            seg: [
              {
                id: 0,
                start: 0,
                stop: 300,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [27, 32, 182],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 2,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
            ],
            n: 'test2',
          },
          '4': {
            playlist: {
              ps: [5, 2],
              dur: [100, 100],
              transition: [7, 7],
              repeat: 0,
              end: 0,
              r: 0,
            },
            on: true,
            n: 'play',
          },
          '3': {
            on: true,
            bri: 128,
            transition: 7,
            mainseg: 0,
            seg: [
              {
                id: 0,
                start: 0,
                stop: 300,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [27, 32, 182],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 2,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
            ],
            n: 'test2',
          },
          '5': {
            on: true,
            bri: 255,
            transition: 7,
            mainseg: 7,
            seg: [
              {
                id: 0,
                start: 0,
                stop: 4,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [27, 32, 182],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 1,
                start: 4,
                stop: 8,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 0, 0],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 2,
                start: 8,
                stop: 12,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 160, 0],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 3,
                start: 12,
                stop: 16,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [0, 255, 200],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 4,
                start: 16,
                stop: 20,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [8, 255, 0],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 5,
                start: 20,
                stop: 24,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 0, 255],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 6,
                start: 24,
                stop: 28,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 255, 255],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 7,
                start: 28,
                stop: 29,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [129, 25, 255],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 0,
                sx: 128,
                ix: 128,
                pal: 0,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
            ],
            n: '7 segments',
          },
          '6': {
            on: true,
            bri: 255,
            transition: 7,
            mainseg: 7,
            seg: [
              {
                id: 0,
                start: 0,
                stop: 4,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [27, 32, 182],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 1,
                start: 4,
                stop: 8,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 0, 0],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 2,
                start: 8,
                stop: 12,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 160, 0],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 3,
                start: 12,
                stop: 16,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [0, 255, 200],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 4,
                start: 16,
                stop: 20,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [8, 255, 0],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 5,
                start: 20,
                stop: 24,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 0, 255],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 6,
                start: 24,
                stop: 28,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [255, 255, 255],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: false,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {
                id: 7,
                start: 28,
                stop: 29,
                grp: 1,
                spc: 0,
                of: 0,
                on: true,
                frz: false,
                bri: 255,
                cct: 127,
                col: [
                  [129, 25, 255],
                  [0, 0, 0],
                  [0, 0, 0],
                ],
                fx: 115,
                sx: 128,
                ix: 128,
                pal: 39,
                c1: 128,
                c2: 128,
                c3: 16,
                sel: true,
                rev: true,
                mi: false,
                o1: false,
                o2: false,
                o3: false,
                si: 0,
                m12: 0,
              },
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
              {stop: 0},
            ],
            n: 'Blends',
          },
        });
    }

    const response = await new Promise<string>((resolve, reject) => {
      this.read(path, resolve, reject);
    });

    console.log('command response: ' + command, response);

    console.log((response as any).state);

    return response;
  }

  async post(command: string, body: string) {
    const path = command.split('/').slice(3).join('/');

    if (path === 'json/state') {
      await BleManager.write(
        this.id,
        WLED_BLE_DATA_SERVICE_ID,
        WLED_BLE_STATE_INFO_DATA_ID,
        this.convertString(body),
      );
    }

    return JSON.stringify({success: true});
  }

  getVersion(): string {
    return this.si?.info?.ver || 'unknown';
  }

  hasBle(): boolean {
    return true;
  }

  isOn(): boolean {
    return !!this.si?.state?.on;
  }

  bright(): number {
    return this.si?.state?.bri || 0;
  }

  getType(): string {
    return 'ble';
  }

  isConnected(): boolean {
    return this.connected;
  }
}
